using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;

public partial class _Default : System.Web.UI.Page
{
    SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString);
   
    
    protected void addmenu_Click(object sender, EventArgs e)
    {
        MultiView1.ActiveViewIndex = 0;
    }

    protected void deletemenu_Click(object sender, EventArgs e)
    {
        MultiView1.ActiveViewIndex = 1;
    }




    protected void menuadd_Click(object sender, EventArgs e)
    {
        try
        {
            con.Open();
            SqlCommand cmd = new SqlCommand("insert into menu values('" + y1.Text + "','" + y2.SelectedItem.Text + "','" + y3.SelectedItem.Text + "','" + y7.Text + "','"+y4.ImageUrl+"')", con);
            cmd.ExecuteNonQuery();
            con.Close();
            m14.Visible = true;
            m14.Text = "your data save successfully";
            y1.Text = "";
            y2.ClearSelection();
            y3.ClearSelection();
            y7.Text="";
            y4.ImageUrl = "";
        }
        catch (Exception e1)
        {
            m14.Visible = true;
            m14.Text = "error=" + e1.Message;
        }
    }

    protected void Page_Load(object sender, EventArgs e)
    {
        autogenerated();
        if (y5.PostedFile != null && y5.PostedFile.ContentLength > 0)
            UpLoadAndDisplay();
    }
    private void UpLoadAndDisplay()
    {
        string imgName = y5.FileName;
        string imgPath = "profile/" + imgName;
        int imgSize = y5.PostedFile.ContentLength;
        if (y5.PostedFile != null && y5.PostedFile.FileName != "")
        {

            y5.SaveAs(Server.MapPath(imgPath));
            y4.ImageUrl = "~/" + imgPath;
        }
    }
    
    void autogenerated()
    {
        int count = 0;
        string str;
        SqlCommand com;
        SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString);

        str = "Select count(dishid) from menu";
        com = new SqlCommand(str, con);
        con.Open();
        count = Convert.ToInt16(com.ExecuteScalar()) + 1;
        y1.Text = "m" + count.ToString();

        con.Close();
    }
    protected void mdelete_Click(object sender, EventArgs e)
    {

                try
        {
            con.Open();
            SqlCommand cmd = new SqlCommand("delete from menu where dishid='" +y9.SelectedItem .Text+ "'", con);
            cmd.ExecuteNonQuery();
            con.Close();
           
            m15.Visible = true;
            m15.Text = "data deleted successfully";
            y9.ClearSelection();
            y1.Text = "";
            y2.ClearSelection();
            y3.ClearSelection();
            y7.Text="";
            y4.ImageUrl = "";
        }
        catch (Exception e1)
        {
            m15.Visible = true;
            m15.Text = "error=" + e1.Message;
        }
    }


   
    protected void y3_SelectedIndexChanged(object sender, EventArgs e)
    {
       
    }
    protected void y2_SelectedIndexChanged(object sender, EventArgs e)
    {
        SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString);
        con.Open();
        SqlDataAdapter Adp = new SqlDataAdapter("select name from detail where dishtype='" + y2.SelectedItem.Text + "' ", con);
        DataTable Dt = new DataTable();
        Adp.Fill(Dt);
        y3.DataSource = Dt;
        y3.DataTextField = "name";
        y3.DataBind();
    }
}
