using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Configuration;


public partial class _Default : System.Web.UI.Page
{
    SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString);
    protected void Page_Load(object sender, EventArgs e)
    {
        autogenerated();
        if (n6.PostedFile != null && n6.PostedFile.ContentLength > 0)
            UpLoadAndDisplay();
        if (n14.PostedFile != null && n14.PostedFile.ContentLength > 0)
            UpLoadAndDisplay1();
    }
    private void UpLoadAndDisplay()
    {
        string imgName = n6.FileName;
        string imgPath = "profile/" + imgName;
        int imgSize = n6.PostedFile.ContentLength;
        if (n6.PostedFile != null && n6.PostedFile.FileName != "")
        {

            n6.SaveAs(Server.MapPath(imgPath));
            n4.ImageUrl = "~/" + imgPath;
        }
    }
    private void UpLoadAndDisplay1()
    {
        string imgName = n14.FileName;
        string imgPath = "profile/" + imgName;
        int imgSize = n14.PostedFile.ContentLength;
        if (n14.PostedFile != null && n14.PostedFile.FileName != "")
        {

            n14.SaveAs(Server.MapPath(imgPath));
            n13.ImageUrl = "~/" + imgPath;
        }





    }
    void autogenerated()
    {
        int count = 0;
        string str;
        SqlCommand com;
        SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString);

        str = "Select count(nonacroomid) from nonacroom";
        com = new SqlCommand(str, con);
        con.Open();
        count = Convert.ToInt16(com.ExecuteScalar()) + 1;
        n5.Text = "n" + count.ToString();

        con.Close();
    }




    protected void n11_Click(object sender, EventArgs e)
    {
        try
        {
            con.Open();
            SqlCommand cmd = new SqlCommand("insert into nonacroom values('" + n5.Text + "','" + n7.Text + "','" + n8.SelectedItem.Text + "','" + n9.SelectedItem.Text + "','" + n10.Text + "','" + n4.ImageUrl + "')", con);
            cmd.ExecuteNonQuery();
            con.Close();
            n25.Visible = true;
            n25.Text = "your data save successfully";
            n5.Text = "";
            n7.Text = "";
            n8.ClearSelection();
            n9.ClearSelection();
            n10.Text = "";
            n4.ImageUrl = "";
        }
        catch (Exception e1)
        {
            n25.Visible = true;
            n25.Text = "error=" + e1.Message;
        }




    }

    protected void anr_Click(object sender, EventArgs e)
    {
        MultiView1.ActiveViewIndex = 0;
    }
    protected void unr_Click(object sender, EventArgs e)
    {
        MultiView1.ActiveViewIndex = 1;
    }
    protected void dnr_Click(object sender, EventArgs e)
    {
        MultiView1.ActiveViewIndex = 2;
    }
    protected void n19_Click(object sender, EventArgs e)
    {
        try
        {
            con.Open();
            SqlCommand cmd = new SqlCommand("select * from nonacroom where nonacroomid='" + n15.SelectedItem.Text + "  ' ", con);
            SqlDataReader reader = cmd.ExecuteReader();
            reader.Read();
            if (reader.HasRows)
            {
                n15.Text = reader[0].ToString();
                n28.Text = reader[1].ToString();
                n16.Text = reader[2].ToString();
                n17.Text = reader[3].ToString();
                n18.Text = reader[4].ToString();
                n13.ImageUrl = reader[5].ToString();
                reader.Close();
                con.Close();
            }
        }
        catch (NullReferenceException ex)
        {
            n26.Visible = true;
            n26.Text = ("Processor Usage" + ex.Message);
        }
    }
    protected void n20_Click(object sender, EventArgs e)
    {
        try
        {
            con.Open();
            SqlCommand cmd = new SqlCommand("update nonacroom set  nonacroomid='" + n15.Text + "', roomsize='" + n28.Text + "', facilities='" + n16.SelectedItem.Text + "',roomrent='" + n17.Text + "',img='" + n13.ImageUrl + "' where nonacroomid='" + (n15.SelectedItem.Text).ToString() + "'", con);
            cmd.ExecuteNonQuery();
            con.Close();

            n26.Visible = true;
            n26.Text = "your data updated successfully";

            n15.ClearSelection();
            n28.Text = "";
            n16.ClearSelection();
            n17.Text = "";
            n18.Text = "";
            n13.ImageUrl = "";

        }
        catch (Exception e1)
        {
            n26.Visible = true;
            n26.Text = "error=" + e1.Message;


        }
    }
    protected void n23_Click(object sender, EventArgs e)
    {
         try
        {
            con.Open();
            SqlCommand cmd = new SqlCommand("delete from nonacroom where nonacroomid='" +n22.SelectedItem .Text+ "'", con);
            cmd.ExecuteNonQuery();
            con.Close();
           
            n27.Visible = true;
            n27.Text = "data deleted successfully";
            n22.ClearSelection();
            n15.ClearSelection();
            n28.Text = "";
            n16.ClearSelection();
            n17.ClearSelection();
            n18.Text="";
            n13.ImageUrl= "";
        }
        catch (Exception e1)
        {
            n27.Visible = true;
            n27.Text = "error=" + e1.Message;
        }
    }

    
}