using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Configuration;

public partial class _Default : System.Web.UI.Page
{
    SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString);
    protected void Page_Load(object sender, EventArgs e)
    {
        autogenerated();
        HiddenField1.Value = Request.QueryString["id"];
    }
    void autogenerated()
    {
        int count = 0;
        string str;
        SqlCommand com;
        SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString);

        str = "Select count(id) from register";
        com = new SqlCommand(str, con);
        con.Open();
        count = Convert.ToInt16(com.ExecuteScalar()) + 1;
        k10.Text = "C00" + count.ToString();

        con.Close();
    }

       

    protected void k8_Click(object sender, EventArgs e)
    {
        if (Request.QueryString != null)
        {
            con.Open();
            SqlCommand cmd = new SqlCommand("insert into register values('" + k10.Text + "','" + k1.Text + "','" + k2.Text + "','" + k3.Text + "','" + k4.Text + "','" + k5.Text + "','" + k6.Text + "','" + k7.SelectedValue + "')", con);
            cmd.ExecuteNonQuery();
            con.Close();
            k11.Visible = true;
            k11.Text = "your data save successfully";
            Response.Redirect("tablebook.aspx?=id" + HiddenField1.Value);
            k10.Text = "";
            k1.Text = "";
            k2.Text = "";
            k3.Text = "";
            k4.Text = "";
            k5.Text = "";
            k6.Text = "";
            k7.ClearSelection();
        }
        else
        {
            con.Open();
            SqlCommand cmd = new SqlCommand("insert into register values('" + k10.Text + "','" + k1.Text + "','" + k2.Text + "','" + k3.Text + "','" + k4.Text + "','" + k5.Text + "','" + k6.Text + "','" + k7.SelectedValue + "')", con);
            cmd.ExecuteNonQuery();
            con.Close();
            k11.Visible = true;
            k11.Text = "your data save successfully";
           
            k10.Text = "";
            k1.Text = "";
            k2.Text = "";
            k3.Text = "";
            k4.Text = "";
            k5.Text = "";
            k6.Text = "";
            k7.ClearSelection();
        }

    }

}