using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Configuration;
using System.Data.SqlClient;
using System.Data;

public partial class _Default : System.Web.UI.Page
{
    SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString);

    protected void Button1_Click2(object sender, EventArgs e)
    {
        MultiView1.ActiveViewIndex = 0;
    }
    protected void Button2_Click2(object sender, EventArgs e)
    {
        MultiView1.ActiveViewIndex = 1;
    }
    protected void Button3_Click2(object sender, EventArgs e)
    {
        MultiView1.ActiveViewIndex = 2;
    }


    protected void staffadd_Click(object sender, EventArgs e)
    {
        try
        {
            con.Open();
            SqlCommand cmd = new SqlCommand("insert into staff values('" + staffid.Text + "','" + staffdept.SelectedItem.Text + "','" + staffpost.SelectedItem.Text + "','" + staffname.Text + "','" + staffaddress.Text + "','" + staffphone.Text + "')", con);
            cmd.ExecuteNonQuery();
            con.Close();
           
            l2.Visible = true;
            l2.Text = "your data save successfully";
            staffid.Text = "";
            staffdept.ClearSelection();
            staffpost.ClearSelection();
            staffname.Text = "";
            staffaddress.Text = "";
            staffphone.Text = "";
            
           
        }
        catch (Exception e1)
        {
            l2.Visible = true;
            l2.Text = "error=" + e1.Message;
        }


    }



    protected void ssearch_Click(object sender, EventArgs e)
    {
        try
        {
            con.Open();
            SqlCommand cmd = new SqlCommand("select * from staff where staffid='" + sid.Text + "  ' ", con);
            SqlDataReader reader = cmd.ExecuteReader();
            reader.Read();
            if (reader.HasRows)
            {
                sid.Text = reader[0].ToString();
                 sdept.Text = reader[1].ToString();
                spost.Text = reader[2].ToString();
                sname .Text = reader[3].ToString();
               saddress .Text = reader[4].ToString();
               sphone.Text = reader[5].ToString();
                reader.Close();
                con.Close();
            }
        }
        catch (NullReferenceException ex)
        {
            l1.Visible = true;
            l1.Text = ("Processor Usage" + ex.Message);
        }
    }

    protected void Page_Load(object sender, EventArgs e)
    {
        autogenerated();
    }
    void autogenerated()
    {
        int count = 0;
        string str;
        SqlCommand com;
        SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString);

        str = "Select count(staffid) from staff";
        com = new SqlCommand(str, con);
        con.Open();
        count = Convert.ToInt16(com.ExecuteScalar()) + 1;
        staffid.Text = "S00" + count.ToString();

        con.Close();
    }
    protected void supdate_Click(object sender, EventArgs e)
    {


            con.Open();
            SqlCommand cmd = new SqlCommand("update staff set staffid='"+sid.Text+"',staffdept='" + sdept.SelectedItem.Text+ "', staffpost='" + spost.SelectedItem.Text + "', staffname='" + sname.Text + "', address='" + saddress.Text + "', phoneno='" + sphone.Text + "' where staffid='" + sid.SelectedItem.Text   + "'", con);
            cmd.ExecuteNonQuery();
            con.Close();
            l1.Visible = true;
            l1.Text = "your data updated successfully";
            sid.ClearSelection();
            sdept.ClearSelection();
            spost.ClearSelection();
            sname.Text = "";
            saddress.Text = "";
            sphone.Text = "";
           
        }
       
    
    protected void delete_Click(object sender, EventArgs e)
    {
         try
        {
            con.Open();
            SqlCommand cmd = new SqlCommand("delete from staff where staffid='" + selectid.SelectedItem.Text + "'", con);
            cmd.ExecuteNonQuery();
            con.Close();
           
            l3.Visible = true;
            l3.Text = "Data Deleted successfully";
            selectid.ClearSelection();
            sdept.ClearSelection();
            spost.ClearSelection();
              sname.Text = "";
              saddress.Text = "";
              sphone.Text = "";
            
        }
        catch (Exception e1)
        {
            l3.Visible = true;
            l3.Text = "error=" + e1.Message;
        }
    }

    
}